service : serverless-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          path: /{proxy+}
          method: any